name: CD

on:
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
      # - name: Get latest code
      #   uses: actions/checkout@v2

      - name: Syncing code with the FTP server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "."
